### ISSUE TITLE
Run on FX18

### ISSUE THREAD

**Issue by jsusito** [betanzos/cross-platform-app-fx#2]
When trying to distribute a project made with this skeleton, the maven gives an error when packaging with javafx 18.

<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <javafx.version>18</javafx.version>
</properties>

clean package  -- Error 

Result:
[INFO] --- maven-assembly-plugin:3.4.1:single (make-assembly) @ cross-platform-app-fx ---
[WARNING] Failed to build parent project for org.openjfx:javafx-base:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-controls:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-graphics:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-base:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-controls:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-graphics:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-base:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-controls:jar:18
[WARNING] Failed to build parent project for org.openjfx:javafx-graphics:jar:18

**Comment by betanzos** [comment]
For me it works fine after changing the value of the property `javafx.version` in the POM from `14` to `18.0.1`. Can you please share the output of the `mvn --version` command?

However, this isn't an error (your build must have been successful) and you can find more info on this link: https://bugs.openjdk.org/browse/JDK-8279327

I am closing this issue because there is no problem with the project, but feel free to reopen if you think it is necessary.
